-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 12:47:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PruebaSIC_Rafael
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PruebaSIC_Rafael
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PruebaSIC_Rafael` DEFAULT CHARACTER SET utf8mb3 ;
USE `PruebaSIC_Rafael` ;

-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`regiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`regiones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`clientes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `create_at` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(12) NOT NULL,
  `region_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_1c96wv36rk2hwui7qhjks3mvg` (`email` ASC) VISIBLE,
  INDEX `FKf1kwxd4whuje3nv9yxddld4c3` (`region_id` ASC) VISIBLE,
  CONSTRAINT `FKf1kwxd4whuje3nv9yxddld4c3`
    FOREIGN KEY (`region_id`)
    REFERENCES `PruebaSIC_Rafael`.`regiones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`facturas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `create_at` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `observacion` VARCHAR(255) NULL DEFAULT NULL,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1qiuk10rfkovhlfpsk7oic0v8` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `FK1qiuk10rfkovhlfpsk7oic0v8`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `PruebaSIC_Rafael`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`productos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `create_at` DATE NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`facturas_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`facturas_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL DEFAULT NULL,
  `producto_id` BIGINT NULL DEFAULT NULL,
  `factura_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdumnm9x14hjfp9fufn7q8389r` (`producto_id` ASC) VISIBLE,
  INDEX `FKnv8ijya20df661b0p6drqcx7u` (`factura_id` ASC) VISIBLE,
  CONSTRAINT `FKdumnm9x14hjfp9fufn7q8389r`
    FOREIGN KEY (`producto_id`)
    REFERENCES `PruebaSIC_Rafael`.`productos` (`id`),
  CONSTRAINT `FKnv8ijya20df661b0p6drqcx7u`
    FOREIGN KEY (`factura_id`)
    REFERENCES `PruebaSIC_Rafael`.`facturas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ldv0v52e0udsh2h1rs0r0gw1n` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` BIT(1) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_kfsp0s1tflm1cwlj8idhqsad0` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_m2dvbwfge291euvmk6vkkocao` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PruebaSIC_Rafael`.`usuarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PruebaSIC_Rafael`.`usuarios_roles` (
  `usuario_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  UNIQUE INDEX `UKqjaspm7473pnu9y4jxhrds8r2` (`usuario_id` ASC, `role_id` ASC) VISIBLE,
  INDEX `FKihom0uklpkfpffipxpoyf7b74` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKihom0uklpkfpffipxpoyf7b74`
    FOREIGN KEY (`role_id`)
    REFERENCES `PruebaSIC_Rafael`.`roles` (`id`),
  CONSTRAINT `FKqcxu02bqipxpr7cjyj9dmhwec`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `PruebaSIC_Rafael`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
